version: "3.1"
services:
  server:
    image: slcloe/jasminback
    ports:
      - "8081:8080"
    container_name: jasmin
    volumes:
      - /etc/letsencrypt/live/mufin.life/keystore.p12:/etc/ssl/certs/keystore.p12
    environment:
      SERVER_PORT: 8080
      SERVER_SSL_KEYSTORE: "/etc/ssl/certs/keystore.p12"
      SERVER_SSL_KEYSTORE_PASSWORD: "ssafy"
      SERVER_SSL_KEYSTORE_TYPE: "PKCS12"
#    environment:
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
#      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
#      SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}
#      WEATHERKEY: ${WEATHERKEY}
#      SCHEDULE_CRON_START: ${SCHEDULE_CRON_START}
#      SCHEDULE_CRON_END: ${SCHEDULE_CRON_END}
#      SCHEDULE_CRON_RANK: ${SCHEDULE_CRON_RANK}
#      SCHEDULE_CRON_TEST: ${SCHEDULE_CRON_TEST}
#      SCHEDULE_USE: ${SCHEDULE_USE}
#      CLOUD_AWS_S3_BUCKET: ${CLOUD_AWS_S3_BUCKET}
#      CLOUD_AWS_STACK_AUTO: ${CLOUD_AWS_STACK_AUTO}
#      CLOUD_AWS_REGOIN_STATIC: ${CLOUD_AWS_REGOIN_STATIC}
#      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
#      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}