spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.c16mgeqgsinu.ap-northeast-2.rds.amazonaws.com:5432/jasumin
    username: jasumin
    password: wktnalsa502

  redis:
    port: 14153
    host: redis-14153.c290.ap-northeast-1-2.ec2.cloud.redislabs.com
    password: TAbJtFFRwTSn33JNcItMNERDl4Se01HU