spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: false
        jdbc:
          time_zone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB